#!/usr/bin/env python
# coding=utf-8
#
# Treex main executable
#
from __future__ import unicode_literals

__author__ = "Ondřej Dušek"
__date__ = "2012"

import sys
from pytreex.core.run import Run

if __name__ == '__main__':
    run = Run(sys.argv[1:])
    run.run()
